---

- name: Include task to create/update Global DNS Policy.
  ansible.builtin.include_tasks: add_dns_policy.yaml
  loop: "{{ fad_dns_policies }}"
  loop_control:
    loop_var: dns_policy
  tags:
    - fad_dns_policy