---

- name: Delete default policy.
  ansible.builtin.import_tasks: delete_default_policy.yaml
  tags: [fad_dns_policy]

- name: Create/update DNS Policy entry.
  vars:
    fad_dns_policy_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_policy }}"
  ansible.builtin.import_tasks: fad_dns_policy.yaml
  tags: [fad_dns_policy]

- name: Update DNS General Settings.
  vars:
    fad_dns_general_settings_api_endpoint: "{{ fad_base_url + fad_api_endpoint.dns_general_settings }}"
  ansible.builtin.import_tasks: fad_dns_general_settings.yaml
  tags: [fad_dns_policy, fad_dns_general_settings]
